version: "3.4"

services:
  alice:
    hostname: alice
    container_name: alice
    image: victim:1.0
    build:
      context: ./build/victim
      dockerfile: ./Dockerfile
    mac_address: 00:00:00:00:00:01
    tty: true
    networks:
      lab-net:
        ipv4_address: 10.10.0.101

  bob:
    image: victim:1.0
    hostname: bob
    container_name: bob
    mac_address: 00:00:00:00:00:02
    tty: true
    networks:
      lab-net:
        ipv4_address: 10.10.0.102

  evie:
    hostname: evie
    container_name: evie
    image: attacker:1.0
    build:
      context: ./build/attacker
      dockerfile: ./Dockerfile
    mac_address: 00:00:00:00:00:03
    tty: true
    # privileged: true
    cap_add:
      - ALL
    networks:
      lab-net:
        ipv4_address: 10.10.0.103

  udpserv:
    hostname: udpserv
    container_name: udpserv
    image: udpserv:1.0
    build:
      context: ./build/udpserver
      dockerfile: ./Dockerfile
    mac_address: 00:00:00:00:00:04
    tty: true
    networks:
      lab-net:
        ipv4_address: 10.10.0.104    


networks:
  lab-net:
    internal: true
    ipam:
      config:
        - subnet: 10.10.0.0/24

